### ISSUE TITLE
Missing plugin

### ISSUE THREAD

**Issue by hgnelson83** [cakephp-fr/recaptcha#10]
I've been trying for the past 2 days to implement this component into my cake 3.2.x live website and I can't make it to work so far.

I am getting a "Missing Plugin
Cake\Core\Exception\MissingPluginException" 

"⟩ Cake\Core\Plugin::load
ROOT/config/bootstrap.php, line 196
⟩ require
ROOT/webroot/index.php, line 27"

I have written in my bootstrap.php file:
"Plugin::load('Recaptcha', ['bootstrap' => true]);"

More errors:
"Error: The application is trying to load a file from the Recaptcha plugin. 
Make sure your plugin Recaptcha is in the /public_html/plugins/ directory and was loaded."

**Comment by HavokInspiration** [comment]
Did you download the plugin using composer e.g. did you do : 

```bash
composer require cakephp-fr/recaptcha
```

**Comment by cake17** [comment]
I close this issue. Please reopen if it still does not work for you
