### ISSUE TITLE
failed to open stream: no suitable wrapper could be found

### ISSUE THREAD

**Issue by super-viny** [cakephp-fr/recaptcha#7]
I used a mutualized server... 

The plugin works fine until I call the method "$this->Recaptcha->verify()".

I get this error:
`fopen(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 fopen(https://www.google.com/recaptcha/api/siteverify): failed to open stream: no suitable wrapper could be found
`

I read that I can turn on "allow_url_fopen" by adding something like "php_value allow_url_fopen On" in the file ".htaccesss" but until now without any success...

**Comment by super-viny** [comment]
OK I eventually found the solution...

In root folder of the project cakephp, I needed to create a file named ".user.ini" with this instruction on it:
allow_url_fopen=On

**Comment by cake17** [comment]
@super-viny thanks for reporting your issue, this seems specific to your hosting service provider but this might help someone else
