### ISSUE TITLE
Error: Class 'Recaptcha\Validation\ConfigValidator' not found 

### ISSUE THREAD

**Issue by Estacio042** [cakephp-fr/recaptcha#9]
how to solve that?
I put the zip file uncomprensed on /Plugins and follow your steps but now gave me this error.

**Comment by cake17** [comment]
This plugin only works with CakePHP 3 and must be installed with Composer: `composer require cakephp-fr/recaptcha:~0.4`

**Comment by Estacio042** [comment]
yes, but doesn't work for me. I'm on cakephp 3.0 and put the "compser require" into composer.json

**Comment by cake17** [comment]
I just tried with a new app like this in the terminal:

```
composer create-project --prefer-dist cakephp/app my_app_name
composer require cakephp-fr/recaptcha:~0.4
bin/cake plugin load -rb Recaptcha
```

And it worked. Would you mind try this code ?

**Comment by Estacio042** [comment]
sorry, is my fault. I putting the code directly into composer.json ... and not running into comand line.

**Comment by cake17** [comment]
@Estacio042 no problem, thanks for reporting
